vich_uploader:
    db_driver: orm

    mappings:
        flight_image:
            uri_prefix: /images/flights
            upload_destination: '%kernel.project_dir%/public/images/uploads'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
